const cartas = [
  {
    name: "False knight",
    attack: 3,
    defense: 9,
    agilidade: 1,
    mana: 0,
    descricao: "Brutal, mas desajeitado com sua maça enferrujada.",
    habilidade: "aa",
  },
  {
    name: "Gruz Mother",
    attack: 3,
    defense: 2,
    agilidade: 4,
    mana: 0,
    descricao: "A maior de todas as mães",
    habilidade: "aa",
  },
  {
    name: "Hornet",
    attack: 7,
    defense: 7,
    agilidade: 10,
    mana: 5,
    descricao: "Ágil e mortal, protege Hallownest com sua agulha afiada.",
    habilidade: "aa",
  },
  {
    name: "Mantis Lords",
    attack: 7,
    defense: 7,
    agilidade: 10,
    mana: 2,
    descricao: "Os denfensores mais hostis da vila dos louva-deuses.",
    habilidade: "aa",
  },
  {
    name: "Soul Master",
    attack: 5,
    defense: 1,
    agilidade: 10,
    mana: 10,
    descricao: "O sabio que enloqueceu e devora as almas dos maiores.",
    habilidade: "aa",
  },
  {
    name: "Dung Defender",
    attack: 8,
    defense: 8,
    agilidade: 8,
    mana: 0,
    descricao: "Um dos maiores guerreiros ja visto em hollowest",
    habilidade: "aa",
  },
  {
    name: "Broken Vessel",
    attack: 7,
    defense: 5,
    agilidade: 5,
    mana: 10,
    descricao: "Será que você ja foi isso ou irá se tornar isso?",
    habilidade: "aa",
  },
  {
    name: "THE WATCHER KNIGHTS",
    attack: 10,
    defense: 3,
    agilidade: 7,
    mana: 5,
    descricao: "Será que você ja foi isso ou irá se tornar isso?",
    habilidade: "aa",
  },
  {
    name: "The Hollow Knight",
    attack: 10,
    defense: 3,
    agilidade: 10,
    mana: 10,
    descricao: "Por que esse foi seu real destino?",
    habilidade: "aa",
  },
  {
    name: "Massive Moss",
    attack: 3,
    defense: 3,
    agilidade: 5,
    mana: 3,
    descricao: "Apenas um inseto coberto de musgo",
    habilidade: "aa",
  },
  {
    name: "Grimm",
    attack: 9,
    defense: 9,
    agilidade: 10,
    mana: 10,
    descricao: "Mestre do ritual escarlate, dança com chamas e sombras.",
    habilidade: "aa",
  },

  {
    name: "Uumuu",
    attack: 5,
    defense: 10,
    agilidade: 1,
    mana: 4,
    descricao:
      "Uma criatura feita de energia instável. Difícil de ferir sem estratégia.",
    habilidade: "aa",
  },
];
